
---
- name: "Playbook to install prometheus and EFK"
  hosts: server
  become: true
  vars:
    system_user: vagrant

  roles:
    - prometheus
    - node_exporter
    - elastic_and_kibana
    - fluentbit



# Install 2nd node_exporter

- name: "server to start install node_exporter only"
  hosts: second
  become: true
  vars:
    node_exporter_version: 1.5.0

  roles:
    - node_exporter

# Update config prometheus.yml file

- name: "Update prometheus.yml config"
  hosts: openvpn
  become: true
  tasks:
  - name: "Insert node_exporter ip in prometheus.yml config"
    lineinfile:
      path: /etc/prometheus/prometheus.yml
      regex: "# add 1st node_exporter"
      insertafter: "^# add 1st node_exporter"
      line: "{{ lookup('template', 'node_exporter.j2') }}"
    notify:
    - Reload systemd unit prometheus

  handlers:
  - name: Reload systemd unit prometheus
    ansible.builtin.systemd:
      daemon-reload: true
      state: reloaded
      name: prometheus