
---
- name: "Playbook to install prometheus and EFK"
  hosts: server
  become: true
  vars:
    system_user: vagrant

  roles:
    - prometheus
    - node_exporter
    - elastic_and_kibana
    - fluentbit

