---
# tasks file for elastic_and_kibana

# Устанавливаем зависимости
- name: "Install dependencies"
  ansible.builtin.package:
    name: apt-transport-https
    state: present

# Добавляем репозиторий Яндекса
- name: "Add Yandex APT repository"
  ansible.builtin.apt_repository:
    repo: "[trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main"
    state: present

# Устанавливаем elasticsearch
- name: "Install Elasticsearch"
  ansible.builtin.apt_repository:
    name: "elasticsearch={{ elastic_ver }}"
    state: present

# Устанавливаем kibana
- name: "Install Kibana"
  ansible.builtin.apt_repository:
    name: "kibana={{ kibana_ver }}"
    state: present

# Стартуем сервис Эластик
- name: "Start systemd service elasticsearch"
  ansible.builtin.systemd:
    daemon-reload: true
    state: started
    enabled: yes
    name: elasticsearch

# Стартуем сервис кибаны
- name: "Start systemd service kibana"
  ansible.builtin.systemd:
    daemon-reload: true
    state: started
    enabled: yes
    name: kibana

# Здесь настраиваем связь elasticsearch и kibana
- include_tasks: aid_auth_elastic.yaml

# Настраиваем конфиг кибаны и перезапускаем её
- name: "Set kibana config file"
  ansible.builtin.template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0660
  notify:
  - Restart systemd kibana
  