---
# handlers file for node_exporter

  - name: "Restart systemd node_exporter"
    ansible.builtin.systemd:
      daemon-reload: true
      state: restarted
      name: node_exporter

  - name: "Reload systemd prometheus"
    ansible.builtin.systemd:
      daemon-reload: true
      state: reloaded
      name: prometheus